export const watches = [
	{
		id: 1,
		brand: "Omega",
		model: "Seamaster",
		type: "Automatic",
		price: 500,
		bestSeler: 1,
		material: "Stainless Steel",
		waterResistance: true,
		features: "Chronometer, Date",
		releaseDate: new Date("2020-06-15"),
		images: [
			"https://example.com/images/omega_seamaster_1.jpg",
			"https://example.com/images/omega_seamaster_2.jpg",
		],
		description: "A classic dive watch with exceptional accuracy and water resistance.",
		stockQuantity: 10,
	},
	{
		id: 2,
		brand: "Rolex",
		model: "Submariner",
		type: "Automatic",
		price: 850,
		bestSeler: 1,
		material: "Gold",
		waterResistance: true,
		features: "Chronometer, Date, Rotating Bezel",
		releaseDate: new Date("2019-04-10"),
		images: [
			"https://example.com/images/rolex_submariner_1.jpg",
			"https://example.com/images/rolex_submariner_2.jpg",
		],
		description: "The ultimate luxury dive watch, renowned for its precision and durability.",
		stockQuantity: 5,
	},
	{
		id: 3,
		brand: "Seiko",
		model: "Prospex",
		type: "Solar",
		price: 620,
		bestSeler: 0,
		material: "Titanium",
		waterResistance: true,
		features: "Chronograph, Alarm, Date",
		releaseDate: new Date("2021-11-05"),
		images: ["https://example.com/images/seiko_prospex_1.jpg", "https://example.com/images/seiko_prospex_2.jpg"],
		description: "A rugged solar-powered watch designed for adventure and exploration.",
		stockQuantity: 20,
	},
	{
		id: 4,
		brand: "Casio",
		model: "G-Shock",
		type: "Digital",
		price: 150,
		bestSeler: 1,
		material: "Resin",
		waterResistance: true,
		features: "Shock Resistant, World Time, Alarm, Timer",
		releaseDate: new Date("2022-02-18"),
		images: ["https://example.com/images/casio_gshock_1.jpg", "https://example.com/images/casio_gshock_2.jpg"],
		description: "A durable and resilient digital watch, perfect for active lifestyles.",
		stockQuantity: 30,
	},
	{
		id: 5,
		brand: "Tag Heuer",
		model: "Carrera",
		type: "Automatic",
		price: 780,
		bestSeler: 0,
		material: "Stainless Steel",
		waterResistance: true,
		features: "Chronograph, Tachymeter",
		releaseDate: new Date("2020-09-25"),
		images: [
			"https://example.com/images/tag_heuer_carrera_1.jpg",
			"https://example.com/images/tag_heuer_carrera_2.jpg",
		],
		description: "A sophisticated racing watch with precise chronograph functions.",
		stockQuantity: 8,
	},
];

export default watches;
